server:
  port: 8082
  servlet:
    context-path: /api/v1/music

spring:
  application:
    name: music-creator-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

# Jamendo API Configuration
jamendo:
  client-id: ${JAMENDO_CLIENT_ID}
  client-secret: ${JAMENDO_CLIENT_SECRET}
  base-url: ${JAMENDO_BASE_URL:https://api.jamendo.com/v3}

# Music Storage Configuration
music:
  storage:
    base-directory: ${MUSIC_STORAGE_DIR:/tmp/music}
    max-file-size: 50MB
    allowed-formats: mp3,wav,flac,m4a
  processing:
    max-concurrent-downloads: 5
    download-timeout-minutes: 10

# Logging Configuration
logging:
  level:
    com.contentorganizer.music: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method 