server:
  port: 8084
  servlet:
    context-path: /api/v1/youtube

spring:
  application:
    name: youtube-service
  profiles:
    active: dev
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:youtube_service_db}
      username: ${SPRING_DATA_MONGODB_USERNAME:}
      password: ${SPRING_DATA_MONGODB_PASSWORD:}

# YouTube Configuration
youtube:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    refresh-token: ${GOOGLE_REFRESH_TOKEN}
  stream:
    key: ${YOUTUBE_STREAM_KEY}
    rtmp-url: "rtmp://a.rtmp.youtube.com/live2"
    timeout-seconds: 120
    ffmpeg-path: "ffmpeg"
    default-resolution: "1920x1080"
    default-fps: 30
    default-bitrate: 4000
    default-audio-codec: "aac"
    default-video-codec: "libx264"
  upload:
    max-file-size: 10737418240  # 10GB
    allowed-formats: mp4,avi,mov,mkv,webm
  retry:
    max-attempts: 3
    delay-millis: 1000
    multiplier: 2.0

# Logging
logging:
  level:
    com.contentorganizer.youtube: DEBUG
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method 