server:
  port: 8084
  servlet:
    context-path: /api/v1/youtube

spring:
  application:
    name: youtube-service

# YouTube API Configuration
youtube:
  api-key: ${YOUTUBE_API_KEY}
  client-id: ${YOUTUBE_CLIENT_ID}
  client-secret: ${YOUTUBE_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.contentorganizer.youtube: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method 